Repository LikeLion-team10/Mat-ZIP, pull requests merged in 2023-07, with the labels that each got.

#44 S3 이미지 naming 정책 수정
  src/main/java/site/matzip/image/domain/ReviewImage.java
  src/main/java/site/matzip/image/service/ReviewImageService.java
Labels: 🌟feature

#43 나의 맛집지도 만들기
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/domain/Matzip.java
  src/main/java/site/matzip/matzip/dto/MatzipListDTO.java
  src/main/java/site/matzip/matzip/repository/MatzipMemberRepository.java
  src/main/java/site/matzip/matzip/repository/MatzipRepository.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/repository/ReviewRepository.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/matzip/create.html
  src/main/resources/templates/matzip/list.html
  src/main/resources/templates/matzip/mylist.html
  src/main/resources/templates/review/createDev.html
Labels: 🌟feature

#29 Comment 작성 / 수정 / 삭제
  src/main/java/site/matzip/comment/controller/CommentController.java
  src/main/java/site/matzip/comment/domain/Comment.java
  src/main/java/site/matzip/comment/dto/CommentInfoDTO.java
  src/main/java/site/matzip/comment/repository/CommentRepository.java
  src/main/java/site/matzip/comment/service/CommentService.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/member/domain/Member.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/domain/Review.java
  src/main/java/site/matzip/review/dto/ReviewDetailDTO.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/comment/create.html
  src/main/resources/templates/review/detail.html
Labels: 🌟feature, 📄view

#45 merge 충돌 이슈 해결
  src/main/java/site/matzip/review/controller/ReviewController.java
Labels: 🔨fix

#47 Builder 제거
  src/main/java/site/matzip/comment/dto/CommentInfoDTO.java
Labels: 🔨fix

#49 리뷰, 댓글 프로필 이미지
  src/main/java/site/matzip/comment/dto/CommentInfoDTO.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/dto/ReviewDetailDTO.java
  src/main/java/site/matzip/review/dto/ReviewListDTO.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/matzip/list.html
  src/main/resources/templates/matzip/mylist.html
  src/main/resources/templates/review/detail.html
Labels: 🌟feature, 🔥refactor

#50 뱃지 Entity, Repository 추가
  src/main/java/site/matzip/badge/domain/Badge.java
  src/main/java/site/matzip/badge/domain/BadgeType.java
  src/main/java/site/matzip/badge/domain/MemberBadge.java
  src/main/java/site/matzip/badge/repository/BadgeRepository.java
  src/main/java/site/matzip/badge/repository/MemberBadgeRepository.java
  src/main/java/site/matzip/badge/service/MemberBadgeService.java
Labels: 🌟feature

#51 로고 이미지 추가
  src/main/resources/static/img/logo.png
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/review/add.html
  src/main/resources/templates/review/create.html
  src/main/resources/templates/review/createDev.html
  src/main/resources/templates/review/detail.html
  src/main/resources/templates/usr/member/myPage.html
  src/main/resources/templates/usr/member/myPage/modifyNickname.html
  src/main/resources/templates/usr/member/myPage/modifyProfileImage.html
Labels: 📄view

#46 조회수 생성 / 구현
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/domain/Review.java
  src/main/java/site/matzip/review/dto/ReviewDetailDTO.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/matzip/list.html
  src/main/resources/templates/review/detail.html
Labels: 🌟feature, 📄view

#52 } 누락 수정
  src/main/java/site/matzip/review/service/ReviewService.java
Labels: 🔨fix

#48 맛집 타입,이름, 주소로 검색기능 구현
  src/main/java/site/matzip/matzip/domain/MatzipType.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/matzip/create.html
  src/main/resources/templates/matzip/list.html
Labels: 🌟feature

#53 포인트 적립
  src/main/java/site/matzip/MatzipApplication.java
  src/main/java/site/matzip/base/appConfig/AppConfig.java
  src/main/java/site/matzip/comment/domain/Comment.java
  src/main/java/site/matzip/comment/repository/CommentRepository.java
  src/main/java/site/matzip/comment/service/CommentService.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/java/site/matzip/member/domain/Member.java
  src/main/java/site/matzip/review/domain/Review.java
  src/main/java/site/matzip/review/repository/ReviewRepository.java
  src/main/java/site/matzip/review/service/ReviewService.java
Labels: 🌟feature

#58 뱃지 갱신 Scheduling Service 구현 #56
  src/main/java/site/matzip/MatzipApplication.java
  src/main/java/site/matzip/badge/domain/Badge.java
  src/main/java/site/matzip/badge/domain/MemberBadge.java
  src/main/java/site/matzip/badge/repository/BadgeRepository.java
  src/main/java/site/matzip/badge/repository/MemberBadgeRepository.java
  src/main/java/site/matzip/badge/service/MemberBadgeService.java
  src/main/java/site/matzip/comment/repository/CommentRepository.java
  src/main/java/site/matzip/matzip/domain/MatzipMember.java
  src/main/java/site/matzip/matzip/repository/MatzipMemberRepository.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/member/domain/Member.java
  src/main/java/site/matzip/member/repository/MemberRepository.java
  src/main/java/site/matzip/review/repository/ReviewRepository.java
Labels: 🌟feature, 🔨fix

#60 마이페이지 뱃지 출력
  src/main/java/site/matzip/badge/domain/BadgeType.java
  src/main/java/site/matzip/badge/repository/MemberBadgeRepository.java
  src/main/java/site/matzip/badge/service/MemberBadgeService.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/java/site/matzip/member/dto/MemberInfoDTO.java
  src/main/resources/templates/usr/member/myPage.html
Labels: 🌟feature, 📄view

#55 알림 기능
  src/main/java/site/matzip/base/event/EventAfterComment.java
  src/main/java/site/matzip/comment/service/CommentService.java
  src/main/java/site/matzip/notification/controller/NotificationController.java
  src/main/java/site/matzip/notification/dto/NotificationDTO.java
  src/main/java/site/matzip/notification/entity/Notification.java
  src/main/java/site/matzip/notification/eventListener/NotificationEventListener.java
  src/main/java/site/matzip/notification/repository/NotificationRepository.java
  src/main/java/site/matzip/notification/service/NotificationService.java
  src/main/resources/templates/usr/notification/list.html
Labels: 🌟feature

#62 Controller 메서드에 로깅 AOP 적용
  src/main/java/site/matzip/MatzipApplication.java
  src/main/java/site/matzip/badge/service/MemberBadgeService.java
  src/main/java/site/matzip/logging/LoggingAspect.java
Labels: 🌟feature

#63 친구 추가 기능
  src/main/java/site/matzip/base/event/EventAfterFriendRequestAccept.java
  src/main/java/site/matzip/friend/controller/FriendController.java
  src/main/java/site/matzip/friend/dto/FriendDTO.java
  src/main/java/site/matzip/friend/entity/Friend.java
  src/main/java/site/matzip/friend/eventListener/FriendEventListener.java
  src/main/java/site/matzip/friend/repository/FriendRepository.java
  src/main/java/site/matzip/friend/service/FriendService.java
  src/main/java/site/matzip/friendRequest/controller/FriendRequestController.java
  src/main/java/site/matzip/friendRequest/dto/FriendRequestDTO.java
  src/main/java/site/matzip/friendRequest/entity/FriendRequest.java
  src/main/java/site/matzip/friendRequest/repository/FriendRequestRepository.java
  src/main/java/site/matzip/friendRequest/service/FriendRequestService.java
  src/main/java/site/matzip/member/domain/Member.java
  src/main/resources/templates/usr/friend/list.html
  src/main/resources/templates/usr/friend/requestForm.html
  src/main/resources/templates/usr/friend/requestList.html
Labels: 🌟feature

#61 랭킹 조회
  src/main/java/site/matzip/badge/repository/MemberBadgeRepository.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/java/site/matzip/member/dto/MemberProfileDTO.java
  src/main/java/site/matzip/member/dto/MemberRankDTO.java
  src/main/java/site/matzip/member/repository/MemberRepository.java
  src/main/java/site/matzip/member/service/MemberService.java
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/usr/member/ranking.html
Labels: 🌟feature, 📄view

#66 리뷰 좋아요 기능 추가
  src/main/java/site/matzip/member/domain/Member.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/domain/Heart.java
  src/main/java/site/matzip/review/domain/Review.java
  src/main/java/site/matzip/review/dto/ReviewDetailDTO.java
  src/main/java/site/matzip/review/repository/HeartRepository.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/review/detail.html
Labels: 🌟feature, 📄view

#68 Review 수정 / 삭제
  src/main/java/site/matzip/comment/controller/CommentController.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/domain/Review.java
  src/main/java/site/matzip/review/dto/ReviewDetailDTO.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/review/add.html
  src/main/resources/templates/review/detail.html
Labels: 🌟feature, 📄view

#72 리뷰 리스트에 맛집수 친구수 리뷰수 출력
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/review/dto/ReviewListDTO.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/matzip/list.html
Labels: 📄view

#73 친구 요청 알림창
  src/main/java/site/matzip/friendRequest/controller/FriendRequestController.java
  src/main/java/site/matzip/notification/controller/NotificationController.java
  src/main/resources/static/resource/notificationModal.css
  src/main/resources/templates/common/fragments/config.html
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/common/layout/defaultLayout.html
  src/main/resources/templates/usr/friend/requestList.html
  src/main/resources/templates/usr/notification/list.html
  src/main/resources/templates/usr/notification/reviewList.html
Labels: 📄view

#70 마이 페이지 디자인 수정
  src/main/java/site/matzip/base/rq/Rq.java
  src/main/java/site/matzip/friend/controller/FriendController.java
  src/main/java/site/matzip/friend/dto/FriendDetailDTO.java
  src/main/java/site/matzip/friend/repository/FriendRepository.java
  src/main/java/site/matzip/friend/service/FriendService.java
  src/main/java/site/matzip/friendRequest/controller/FriendRequestController.java
  src/main/java/site/matzip/friendRequest/service/FriendRequestService.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/domain/Matzip.java
  src/main/java/site/matzip/matzip/domain/MatzipMember.java
  src/main/java/site/matzip/matzip/domain/MatzipType.java
  src/main/java/site/matzip/matzip/repository/MatzipRepository.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/java/site/matzip/member/dto/MemberInfoCntDTO.java
  src/main/java/site/matzip/member/dto/MemberPointDTO.java
  src/main/java/site/matzip/member/dto/MemberRankDTO.java
  src/main/java/site/matzip/member/dto/MemberRankInfoDTO.java
  src/main/java/site/matzip/member/repository/MemberRepository.java
  src/main/java/site/matzip/member/service/MemberService.java
  src/main/java/site/matzip/notification/controller/NotificationController.java
  src/main/java/site/matzip/review/dto/MyReviewDTO.java
  src/main/resources/static/resource/tabmenu.css
  src/main/resources/templates/usr/member/myPage.html
  src/main/resources/templates/usr/member/myPage/friend.html
  src/main/resources/templates/usr/member/myPage/matzip.html
  src/main/resources/templates/usr/member/myPage/point.html
  src/main/resources/templates/usr/member/myPage/review.html
Labels: 🌟feature, 📄view

#74 incompatible types 문제 해결
  src/main/java/site/matzip/friendRequest/controller/FriendRequestController.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/notification/controller/NotificationController.java
Labels: 🐞bug, 🔨fix

#64 컨트롤러 분리 및 성능 향상 위해 view 함수 분리
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/domain/Matzip.java
  src/main/java/site/matzip/matzip/repository/MatzipMemberRepository.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/repository/ReviewRepository.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/matzip/list.html
  src/main/resources/templates/matzip/mylist.html
Labels: 🌟feature, 🔥refactor

#71 Review 수정시 기존 이미지 출력 / 리뷰 이미지 수정
  src/main/java/site/matzip/image/service/ReviewImageService.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/dto/ReviewCreationDTO.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/review/add.html
Labels: 🌟feature, 📄view

#75 Validation 추가
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/dto/MatzipCreationDTO.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/java/site/matzip/member/dto/MemberRankDTO.java
  src/main/java/site/matzip/review/dto/ReviewCreationDTO.java
Labels: 🌟feature

#67 푸터 디자인
  src/main/resources/templates/common/fragments/footer.html
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/common/layout/defaultLayout.html
  src/main/resources/templates/matzip/list.html
Labels: 📄view

#81 폰트 변경 & 에러 페이지 추가
  src/main/resources/static/common/common.css
  src/main/resources/templates/error/400.html
  src/main/resources/templates/error/401.html
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/500.html
Labels: 📄view

#82 레이아웃 및 UI수정
  src/main/java/site/matzip/matzip/dto/MatzipCreationDTO.java
  src/main/resources/static/img/logo.png
  src/main/resources/templates/common/fragments/footer.html
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/matzip/list.html
Labels: 📄view

#83 리뷰리스트에 업로드한 사진보여주기
  src/main/java/site/matzip/review/dto/ReviewListDTO.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/matzip/list.html
Labels: 📄view

#84 맛집랭킹 / 랭킹 병합 / 각종 디자인 수정
  src/main/java/site/matzip/home/HomeController.java
  src/main/java/site/matzip/map/MapController.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/dto/MatzipRankDTO.java
  src/main/java/site/matzip/matzip/repository/MatzipRepository.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/java/site/matzip/review/dto/ReviewDetailDTO.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/common/fragments/footer.html
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/matzip/list.html
  src/main/resources/templates/ranking/ranking.html
  src/main/resources/templates/review/add.html
  src/main/resources/templates/review/create.html
  src/main/resources/templates/review/detail.html
  src/main/resources/templates/usr/member/ranking.html
Labels: 🌟feature, 📄view

#85 맛집 설명 및 평점 수정
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/dto/MatzipUpdateDTO.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/resources/templates/matzip/create.html
  src/main/resources/templates/matzip/list.html
Labels: 🌟feature

#86 리뷰 등록 Validation & redirect 메서드 Rq 메시지 출력
  README.md
  src/main/java/site/matzip/comment/controller/CommentController.java
  src/main/java/site/matzip/friend/controller/FriendController.java
  src/main/java/site/matzip/friendRequest/controller/FriendRequestController.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/dto/MatzipReviewDTO.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/dto/ReviewCreationDTO.java
Labels: 🌟feature, 📄view

#88 리뷰 리스트 정렬
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/dto/MatzipListDTO.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/service/ReviewService.java
Labels: 🌟feature

#89 맛집 update-> modify
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/domain/MatzipMember.java
  src/main/java/site/matzip/matzip/dto/MatzipModifyDTO.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/resources/templates/matzip/create.html
  src/main/resources/templates/matzip/list.html
Labels: 🔥refactor

#93 맛집 리뷰 동시에 작성 안되던 문제 해결
  src/main/java/site/matzip/base/exception/GlobalExceptionHandler.java
  src/main/java/site/matzip/base/exception/UnauthorizedException.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/dto/MatzipCreationDTO.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/matzip/list.html
  src/main/resources/templates/review/create.html
Labels: 🔨fix

#96 rq -> PrincipalDetails 수정
  src/main/java/site/matzip/friend/controller/FriendController.java
  src/main/java/site/matzip/friendRequest/controller/FriendRequestController.java
  src/main/java/site/matzip/home/HomeController.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/java/site/matzip/notification/controller/NotificationController.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/resources/templates/common/fragments/header.html
Labels: 🔥refactor

#97 @GetMapping("/") 추가
  src/main/java/site/matzip/home/HomeController.java
Labels: 🔨fix

#95 맛집 지도 인포윈도우에 평균점수 표시 및 친구페이지 view 수정
  src/main/java/site/matzip/config/SecurityConfig.java
  src/main/resources/templates/matzip/list.html
  src/main/resources/templates/usr/member/myPage.html
Labels: 🔥refactor, 📄view

#92 리뷰 테스트 코드 작성
  src/main/java/site/matzip/badge/domain/BadgeType.java
  src/main/java/site/matzip/badge/domain/MemberBadge.java
  src/main/java/site/matzip/badge/service/MemberBadgeService.java
  src/main/java/site/matzip/base/domain/BaseEntity.java
  src/main/java/site/matzip/base/rq/Rq.java
  src/main/java/site/matzip/comment/controller/CommentController.java
  src/main/java/site/matzip/comment/repository/CommentRepository.java
  src/main/java/site/matzip/comment/service/CommentService.java
  src/main/java/site/matzip/friend/controller/FriendController.java
  src/main/java/site/matzip/friendRequest/controller/FriendRequestController.java
  src/main/java/site/matzip/image/repository/ReviewImageRepository.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/domain/Matzip.java
  src/main/java/site/matzip/matzip/dto/MatzipCreationDTO.java
  src/main/java/site/matzip/matzip/dto/MatzipReviewDTO.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/java/site/matzip/member/domain/Member.java
  src/main/java/site/matzip/member/dto/MemberRankDTO.java
  src/main/java/site/matzip/member/dto/NicknameUpdateDTO.java
  src/main/java/site/matzip/member/repository/MemberRepository.java
  src/main/java/site/matzip/member/service/MemberService.java
  src/main/java/site/matzip/notification/dto/NotificationDTO.java
  src/main/java/site/matzip/notification/service/NotificationService.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/domain/Review.java
  src/main/java/site/matzip/review/dto/ReviewCreationDTO.java
  src/main/java/site/matzip/review/dto/ReviewListDTO.java
  src/main/java/site/matzip/review/repository/ReviewRepository.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/review/add.html
  src/test/java/site/matzip/review/service/ReviewServiceTest.java
Labels: 🧪test

#100 컨펌창 커스텀
  src/main/java/site/matzip/home/HomeController.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/dto/MatzipCreationDTO.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/resources/static/common/common.js
  src/main/resources/templates/common/fragments/config.html
  src/main/resources/templates/matzip/create.html
  src/main/resources/templates/matzip/list.html
Labels: 🔨fix, 📄view

#101 html 경로 수정 / myPage 파일명 중복 제거
  src/main/java/site/matzip/home/HomeController.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/resources/templates/usr/member/myPage2.html
Labels: 🐞bug, 🔨fix, 📄view

#102 import 누락
  src/main/java/site/matzip/matzip/dto/MatzipCreationDTO.java
Labels: 🔨fix

#103 url 경로 수정
  src/main/resources/templates/usr/member/myPage2.html
Labels: 🔨fix

#99 연관관계 편의 메서드 네이밍 변경 & Service Transaction 어노테이션 수정
  src/main/java/site/matzip/badge/domain/MemberBadge.java
  src/main/java/site/matzip/badge/service/MemberBadgeService.java
  src/main/java/site/matzip/comment/domain/Comment.java
  src/main/java/site/matzip/comment/service/CommentService.java
  src/main/java/site/matzip/friend/domain/Friend.java
  src/main/java/site/matzip/friend/repository/FriendRepository.java
  src/main/java/site/matzip/friend/service/FriendService.java
  src/main/java/site/matzip/friendRequest/controller/FriendRequestController.java
  src/main/java/site/matzip/friendRequest/domain/FriendRequest.java
  src/main/java/site/matzip/friendRequest/repository/FriendRequestRepository.java
  src/main/java/site/matzip/friendRequest/service/FriendRequestService.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/domain/Matzip.java
  src/main/java/site/matzip/matzip/domain/MatzipMember.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/member/domain/Member.java
  src/main/java/site/matzip/member/service/MemberService.java
  src/main/java/site/matzip/notification/domain/Notification.java
  src/main/java/site/matzip/notification/repository/NotificationRepository.java
  src/main/java/site/matzip/notification/service/NotificationService.java
  src/main/java/site/matzip/review/domain/Heart.java
  src/main/java/site/matzip/review/domain/Review.java
  src/main/java/site/matzip/review/service/ReviewService.java
Labels: 🔨fix, 🔥refactor

#104 등록 지도 크기 수정
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/matzip/create.html
  src/main/resources/templates/matzip/list.html
  src/main/resources/templates/usr/member/myPage/modifyNickname.html
  src/main/resources/templates/usr/member/myPage/modifyProfileImage.html
  src/main/resources/templates/usr/member/myPage2.html
Labels: 📄view

#106 모달창에 친구수 적용 / 컨펌창 디자인 수정
  src/main/java/site/matzip/member/dto/MemberProfileDTO.java
  src/main/java/site/matzip/member/service/MemberService.java
  src/main/resources/static/common/common.js
  src/main/resources/templates/main/main.html
  src/main/resources/templates/ranking/ranking.html
  src/main/resources/templates/review/detail.html
  src/main/resources/templates/usr/member/myPage/friend.html
  src/main/resources/templates/usr/notification/reviewList.html
Labels: 📄view

#107 수정 삭제 버튼 크기 및 위치 조정
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/resources/templates/matzip/list.html
Labels: 📄view

#105 에러 페이지 버튼 디자인 수정 & Title 변경
  src/main/resources/templates/error/400.html
  src/main/resources/templates/error/401.html
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/500.html
  src/main/resources/templates/main/main.html
  src/main/resources/templates/matzip/create.html
  src/main/resources/templates/matzip/list.html
  src/main/resources/templates/ranking/ranking.html
  src/main/resources/templates/review/add.html
  src/main/resources/templates/review/create.html
  src/main/resources/templates/review/detail.html
  src/main/resources/templates/usr/friend/list.html
  src/main/resources/templates/usr/member/myPage/friend.html
  src/main/resources/templates/usr/member/myPage/friendMap.html
  src/main/resources/templates/usr/member/myPage/matzip.html
  src/main/resources/templates/usr/member/myPage/modifyNickname.html
  src/main/resources/templates/usr/member/myPage/modifyProfileImage.html
  src/main/resources/templates/usr/member/myPage/point.html
  src/main/resources/templates/usr/member/myPage/review.html
  src/main/resources/templates/usr/member/myPage2.html
Labels: 📄view

#109 hotfix - 친구 삭제 연관관계 수정
  src/main/java/site/matzip/friend/domain/Friend.java
  src/main/java/site/matzip/friend/service/FriendService.java
  src/main/resources/static/android-icon-144x144.png
  src/main/resources/static/android-icon-192x192.png
  src/main/resources/static/android-icon-36x36.png
  src/main/resources/static/android-icon-48x48.png
  src/main/resources/static/android-icon-72x72.png
  src/main/resources/static/android-icon-96x96.png
  src/main/resources/static/apple-icon-114x114.png
  src/main/resources/static/apple-icon-120x120.png
  src/main/resources/static/apple-icon-144x144.png
  src/main/resources/static/apple-icon-152x152.png
  src/main/resources/static/apple-icon-180x180.png
  src/main/resources/static/apple-icon-57x57.png
  src/main/resources/static/apple-icon-60x60.png
  src/main/resources/static/apple-icon-72x72.png
  src/main/resources/static/apple-icon-76x76.png
  src/main/resources/static/apple-icon-precomposed.png
  src/main/resources/static/apple-icon.png
  src/main/resources/static/browserconfig.xml
  src/main/resources/static/favicon-16x16.png
  src/main/resources/static/favicon-32x32.png
  src/main/resources/static/favicon-96x96.png
  src/main/resources/static/favicon.ico
  src/main/resources/static/manifest.json
  src/main/resources/static/ms-icon-144x144.png
  src/main/resources/static/ms-icon-150x150.png
  src/main/resources/static/ms-icon-310x310.png
  src/main/resources/static/ms-icon-70x70.png
  src/main/resources/templates/common/layout/defaultLayout.html
  src/main/resources/templates/usr/member/myPage2.html
Labels: 🔨fix

#94 리드미 작성
  README.md
Labels: 📄documentation

#111 my리뷰리스트 캐싱키 변경
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🔨fix

#116 조회수 버그 수정
  src/main/java/site/matzip/review/service/ReviewService.java
Labels: 🔨fix

#117 친구 삭제 관련 오류 수정
  src/main/java/site/matzip/member/service/MemberService.java
Labels: 🔨fix

#118 친구 맛지도 불러오기 오류 수정
  src/main/java/site/matzip/friend/dto/FriendDetailDTO.java
  src/main/java/site/matzip/member/service/MemberService.java
  src/main/resources/templates/usr/member/myPage/friend.html
Labels: 🔨fix

#120 지도 리뷰리스트에서 글자 넘침 수정
  src/main/java/site/matzip/review/domain/Review.java
  src/main/resources/templates/matzip/list.html
Labels: 🔥refactor, 📄view

#121 조회수 쿠키 유저아이디 추가 / 메서드 통일
  src/main/java/site/matzip/config/auth/PrincipalDetails.java
  src/main/java/site/matzip/home/HomeController.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/java/site/matzip/notification/controller/NotificationController.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/test/java/site/matzip/review/service/ReviewServiceTest.java
Labels: 🔥refactor
