Repository LikeLion-team10/Mat-ZIP, pull requests merged in 2023-06, with the labels that each got.

#2 카카오지도 API 불러오기
  src/main/java/site/matzip/map/MapController.java
  src/main/resources/application.yml
  src/main/resources/templates/map/map.html
Labels: 🚀feature

#1 게시물 MVC 생성
  .gitignore
  src/main/java/site/matzip/MatzipApplication.java
  src/main/java/site/matzip/base/domain/BaseEntity.java
  src/main/java/site/matzip/comment/domain/Comment.java
  src/main/java/site/matzip/comment/domain/CommentRepository.java
  src/main/java/site/matzip/comment/domain/service/CommentService.java
  src/main/java/site/matzip/commentImage/domain/CommentImage.java
  src/main/java/site/matzip/map/MapController.java
  src/main/java/site/matzip/review/domain/Review.java
  src/main/resources/application.yml
  src/test/java/site/matzip/comment/domain/service/CommentServiceTest.java
Labels: 🚀feature

#5 마커 클릭 시, 식당 정보 가져오기
  src/main/java/site/matzip/base/domain/BaseEntity.java
  src/main/java/site/matzip/comment/domain/Comment.java
  src/main/resources/templates/map/map.html
Labels: 🚀feature

#3 맛집 MVC 생성
  src/main/java/site/matzip/.DS_Store
  src/main/java/site/matzip/base/rsData/RsData.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/domain/Matzip.java
  src/main/java/site/matzip/matzip/domain/MatzipType.java
  src/main/java/site/matzip/matzip/dto/MatzipCreationDTO.java
  src/main/java/site/matzip/matzip/dto/MatzipListDTO.java
  src/main/java/site/matzip/matzip/dto/MatzipRegistrationDTO.java
  src/main/java/site/matzip/matzip/repository/MatzipRepository.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/resources/templates/matzip/create.html
  src/main/resources/templates/matzip/list.html
Labels: 🚀feature

#4 kakao OAuth 로그인 / 회원가입
  src/main/java/site/matzip/config/SecurityConfig.java
  src/main/java/site/matzip/config/auth/PrincipalDetails.java
  src/main/java/site/matzip/config/auth/PrincipalDetailsService.java
  src/main/java/site/matzip/config/auth/UserLoginFailureHandler.java
  src/main/java/site/matzip/config/oauth/PrincipalOAuth2UserService.java
  src/main/java/site/matzip/config/oauth/provider/KakaoUserInfo.java
  src/main/java/site/matzip/config/oauth/provider/OAuth2UserInfo.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/java/site/matzip/member/domain/Member.java
  src/main/java/site/matzip/member/domain/MemberRole.java
  src/main/java/site/matzip/member/repository/MemberRepository.java
  src/main/resources/application.yml
  src/main/resources/static/img/kakao_login_medium_wide.png
  src/main/resources/templates/usr/member/login.html
Labels: 🚀feature

#13 자잘한 버그 수정
  src/main/resources/templates/common/fragments/config.html
  src/main/resources/templates/map/map.html
Labels: 🔨fix

#14 맛집 수정, 삭제
  src/main/java/site/matzip/matzip/dto/MatzipRecomUpdateDTO.java
  src/main/resources/templates/map/map.html
Labels: 🚀feature

#16 맛집으로 등록한 정보들을 나만의 맛집 지도에 표시
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/domain/Matzip.java
  src/main/java/site/matzip/matzip/dto/MatzipCreationDTO.java
  src/main/java/site/matzip/matzip/dto/MatzipListDTO.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/resources/templates/map/map.html
  src/main/resources/templates/matzip/list.html
Labels: 🌟feature

#12 Review 작성
  src/main/java/site/matzip/comment/controller/CommentController.java
  src/main/java/site/matzip/comment/domain/Comment.java
  src/main/java/site/matzip/comment/domain/service/CommentService.java
  src/main/java/site/matzip/comment/dto/CommentCreationDTO.java
  src/main/java/site/matzip/comment/repository/CommentRepository.java
  src/main/java/site/matzip/comment/service/CommentService.java
  src/main/java/site/matzip/matzip/domain/Matzip.java
  src/main/java/site/matzip/matzip/dto/MatzipCreationDTO.java
  src/main/java/site/matzip/matzip/dto/MatzipListDTO.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/member/domain/Member.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/domain/Review.java
  src/main/java/site/matzip/review/dto/ReviewCreationDTO.java
  src/main/java/site/matzip/review/repository/ReviewRepository.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/java/site/matzip/reviewImage/domain/ReviewImage.java
  src/main/resources/templates/comment/create.html
  src/main/resources/templates/review/create.html
  src/test/java/site/matzip/comment/domain/service/CommentServiceTest.java
Labels: 🌟feature

#17 맛집 리스트 관련 설정
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/domain/Matzip.java
  src/main/java/site/matzip/matzip/domain/MatzipRecommendation.java
  src/main/java/site/matzip/matzip/dto/MatzipCreationDTO.java
  src/main/java/site/matzip/matzip/dto/MatzipListDTO.java
  src/main/java/site/matzip/matzip/dto/MatzipReviewDTO.java
  src/main/java/site/matzip/matzip/repository/MatzipRepository.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/member/domain/Member.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/domain/Review.java
  src/main/java/site/matzip/review/dto/ReviewCreationDTO.java
  src/main/java/site/matzip/review/repository/ReviewRepository.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/map/map.html
  src/main/resources/templates/matzip/list.html
  src/main/resources/templates/review/create.html
Labels: 🌟feature

#19 비로그인 상태 맛집등록 요청시 로그인 유도
  src/main/resources/templates/map/map.html
  src/main/resources/templates/usr/member/login.html
Labels: 🌟feature

#18 리뷰 작성 페이지 UI 수정
  src/main/java/site/matzip/base/domain/BaseEntity.java
  src/main/java/site/matzip/config/auth/PrincipalDetails.java
  src/main/java/site/matzip/config/oauth/provider/KakaoUserInfo.java
  src/main/java/site/matzip/config/oauth/provider/OAuth2UserInfo.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/dto/MatzipListDTO.java
  src/main/java/site/matzip/matzip/dto/MatzipRecomUpdateDTO.java
  src/main/java/site/matzip/matzip/repository/MatzipRecommendationRepository.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/java/site/matzip/member/domain/Member.java
  src/main/java/site/matzip/member/service/MemberService.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/domain/Review.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/static/common/common.css
  src/main/resources/templates/common/fragments/config.html
  src/main/resources/templates/map/map.html
  src/main/resources/templates/review/create.html
Labels: 🌟feature

#20 리뷰 리스트 출력
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/repository/ReviewRepository.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/map/map.html
  src/main/resources/templates/matzip/list.html
Labels: 🌟feature

#26 사진 업로드를위한 S3 연결
  build.gradle
  src/main/java/site/matzip/config/S3Config.java
  src/main/java/site/matzip/image/domain/ReviewImage.java
  src/main/java/site/matzip/image/repository/ReviewImageRepository.java
  src/main/java/site/matzip/image/service/ReviewImageService.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/review/domain/Review.java
  src/main/java/site/matzip/review/dto/ReviewCreationDTO.java
  src/main/resources/application.yml
  src/main/resources/templates/review/create.html
Labels: 🌟feature, 📄view

#25 Review 작성(맛집 등록상태)
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/dto/MatzipListDTO.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/dto/ReviewCreationDTO.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/matzip/list.html
  src/main/resources/templates/review/add.html
Labels: 🌟feature

#27 Review 삭제
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/application.yml
Labels: 🌟feature

#28 닉네임 변경 기능 구현
  src/main/java/site/matzip/config/oauth/PrincipalOAuth2UserService.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/java/site/matzip/member/domain/Member.java
  src/main/java/site/matzip/member/dto/MemberInfoDTO.java
  src/main/java/site/matzip/member/dto/NicknameUpdateDTO.java
  src/main/java/site/matzip/member/repository/MemberRepository.java
  src/main/java/site/matzip/member/service/MemberService.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/resources/static/resource/tabmenu.css
  src/main/resources/templates/common/fragments/header.html
  src/main/resources/templates/usr/member/myPage.html
  src/main/resources/templates/usr/member/myPage/modifyNickname.html
Labels: 🌟feature

#30 Matzip 엔티티 대신 DTO를 사용해 뷰로 데이터 전달
  src/main/java/site/matzip/matzip/dto/MatzipInfoDTO.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/resources/templates/map/map.html
  src/main/resources/templates/review/add.html
Labels: 🔥refactor

#33 layout 디자인 변경 V1
  src/main/resources/templates/common/fragments/header.html
Labels: 📄view

#31 리뷰 리스트 출력
  src/main/java/site/matzip/base/rq/Rq.java
  src/main/java/site/matzip/config/auth/PrincipalDetails.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/domain/Matzip.java
  src/main/java/site/matzip/matzip/dto/MatzipListDTO.java
  src/main/java/site/matzip/matzip/dto/MatzipReviewListDTO.java
  src/main/java/site/matzip/matzip/repository/MatzipRepository.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/domain/Review.java
  src/main/java/site/matzip/review/dto/ReviewListDTO.java
  src/main/java/site/matzip/review/repository/ReviewRepository.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/application.yml
  src/main/resources/templates/map/map.html
  src/main/resources/templates/matzip/list.html
  src/main/resources/templates/matzip/mylist.html
Labels: 🌟feature

#36 fix: import 추가, 메소드명 변경
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/service/ReviewService.java
Labels: 🔨fix

#38 마커 클릭시 리뷰 리스트 출력
  src/main/java/site/matzip/map/MapController.java
  src/main/resources/templates/matzip/list.html
Labels: 🌟feature

#32 프로필 이미지 변경
  src/main/java/site/matzip/base/appConfig/AppConfig.java
  src/main/java/site/matzip/image/domain/ProfileImage.java
  src/main/java/site/matzip/image/repository/ProfileImageRepository.java
  src/main/java/site/matzip/image/service/ProfileImageService.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/java/site/matzip/member/domain/Member.java
  src/main/java/site/matzip/member/dto/MemberInfoDTO.java
  src/main/resources/templates/usr/member/myPage.html
  src/main/resources/templates/usr/member/myPage/modifyProfileImage.html
Labels: 🌟feature

#39 S3 보안설정 수정과 ReviewImage 로직 수정&적용
  src/main/java/site/matzip/image/domain/ReviewImage.java
  src/main/java/site/matzip/image/service/ReviewImageService.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/domain/Matzip.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/member/domain/Member.java
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/domain/Review.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/review/createDev.html
Labels: 🌟feature, ⚙️setting

#37 리뷰 페이지 UI 적용
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/review/dto/ReviewListDTO.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/common/layout/defaultLayout.html
  src/main/resources/templates/matzip/list.html
Labels: 🌟feature, 📄view

#40 파일 이름 변경 및 이동, 맛집 등록시 list 센터 조정
  src/main/java/site/matzip/config/oauth/CustomUserDetailsService.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/domain/Matzip.java
  src/main/java/site/matzip/matzip/domain/MatzipMember.java
  src/main/java/site/matzip/matzip/dto/MatzipRecomUpdateDTO.java
  src/main/java/site/matzip/matzip/repository/MatzipMemberRepository.java
  src/main/java/site/matzip/matzip/repository/MatzipRecommendationRepository.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/member/domain/Member.java
  src/main/resources/templates/map/map.html
  src/main/resources/templates/matzip/create.html
  src/main/resources/templates/matzip/list.html
  src/main/resources/templates/matzip/mylist.html
Labels: 🌟feature, 🔥refactor

#41 import 중복, 패키지 오류 수정
  src/main/java/site/matzip/config/SecurityConfig.java
  src/main/java/site/matzip/config/auth/PrincipalDetails.java
  src/main/java/site/matzip/matzip/controller/MatzipController.java
  src/main/java/site/matzip/matzip/domain/Matzip.java
  src/main/java/site/matzip/matzip/service/MatzipService.java
  src/main/java/site/matzip/member/controller/MemberController.java
  src/main/java/site/matzip/member/domain/Member.java
  src/main/java/site/matzip/review/domain/Review.java
Labels: 🐞bug, 🔨fix

#42 리뷰 상세페이지 UI 1차 적용
  src/main/java/site/matzip/review/controller/ReviewController.java
  src/main/java/site/matzip/review/dto/ReviewDetailDTO.java
  src/main/java/site/matzip/review/dto/ReviewListDTO.java
  src/main/java/site/matzip/review/service/ReviewService.java
  src/main/resources/templates/matzip/list.html
  src/main/resources/templates/review/detail.html
Labels: 🌟feature, 📄view
